import: Activiti/activiti-scripts:.travis.java.yml@master

stages:
- name: verify
- name: tag_deploy_updatebot
  if: type != pull_request

  
jobs:
  include:
  - name: Reverse and Random order tests
    stage: test
    script:
    - mvn test -Dsurefire.runOrder=reversealphabetical
    - mvn test -Dsurefire.runOrder=random

